### ISSUE TITLE
Need Cord Conduits for the Makerspace

### ISSUE THREAD

**Issue by jgordon510** [jeffreygordon/ebia-issues#10]
We need a cord conduit and extension cord for the projector in the makerspace. 

Conduit:
https://www.amazon.com/Cables-16330-Conduct-floor-Protector/dp/B000IOBL2E/ref=sr_1_1?ie=UTF8&qid=1483727337&sr=8-1&keywords=cord+conduit+floor

Cord:
https://www.amazon.com/Tripp-Lite-Standard-Extension-P022-015/dp/B005KG3Y4I/ref=sr_1_3?ie=UTF8&qid=1483727432&sr=8-3&keywords=15%27+extension+cord

**Comment by jeffreygordon** [comment]
Ordered.

**Comment by jeffreygordon** [comment]
Recd.
