### ISSUE TITLE
LS CB Won't Turn On 

### ISSUE THREAD

**Issue by jeffreygordon** [jeffreygordon/ebia-issues#79]
NXSHEAA0044220CCDC7600
JR
Won't turn on.  Blinky with reflash buttons; no blinky on normal power buttons.

**Comment by jeffreygordon** [comment]
Possible re-repair.  Please check closely in future.

**Comment by minibradford** [comment]
Returned April 14

Mainboard replaced, lcd cable, lcd bezel, lcd cover, lower case and upper case.

Needs new label
